// <auto-generated />
using System;
using ManyToMany;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManyToMany.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201119134519_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ManyToMany.IdentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentDatas");
                });

            modelBuilder.Entity("ManyToMany.IdentDataSubject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("IdentDataId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId", "IdentDataId");

                    b.HasIndex("IdentDataId");

                    b.ToTable("IdentDataSubject");
                });

            modelBuilder.Entity("ManyToMany.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ManyToMany.IdentDataSubject", b =>
                {
                    b.HasOne("ManyToMany.IdentData", "Ident")
                        .WithMany("IdentDataSubjects")
                        .HasForeignKey("IdentDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManyToMany.Subject", "Subject")
                        .WithMany("IdentDataSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ident");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ManyToMany.IdentData", b =>
                {
                    b.Navigation("IdentDataSubjects");
                });

            modelBuilder.Entity("ManyToMany.Subject", b =>
                {
                    b.Navigation("IdentDataSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
